import { z } from 'zod'
import { createRequire } from 'module'
import path from 'path'
import { fileURLToPath } from 'url'

const requireFn = (() => {
  try {
    const currentDir = typeof __dirname !== 'undefined'
      ? __dirname
      : path.dirname(fileURLToPath(import.meta.url))
    const agentPackageJson = path.resolve(currentDir, '../../../agent/package.json')
    return createRequire(agentPackageJson)
  } catch {}
  if (typeof require !== 'undefined') {
    return require
  }
  try {
    return createRequire(path.resolve(process.cwd(), 'package.json'))
  } catch {}
  return createRequire(import.meta.url)
})()

export const name = 'document_gen'

export const description = 'Generate a document in markdown format with optional metadata. Supports various document types like reports, summaries, and notes.'

export const schema = z.object({
  title: z.string().min(1).describe('The document title'),
  content: z.string().min(1).describe('The document content in markdown format'),
  type: z.enum(['report', 'summary', 'note', 'technical']).default('note').describe('The type of document'),
  tags: z.array(z.string()).default([]).describe('Optional tags for the document'),
  format: z.enum(['markdown', 'pdf', 'docx', 'xlsx']).default('markdown').describe('The output format'),
})

export async function generatePdf(title: string, content: string): Promise<Buffer> {
  const PDFDocument = requireFn('pdfkit')
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument()
    const chunks: Buffer[] = []
    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)
    doc.fontSize(20).text(title, { align: 'center' })
    doc.moveDown()
    doc.fontSize(12).text(content)
    doc.end()
  })
}

export async function generateDocx(title: string, content: string): Promise<Buffer> {
  const { Document, Paragraph, HeadingLevel, Packer } = await import('docx')
  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ text: title, heading: HeadingLevel.TITLE }),
        new Paragraph({ text: content }),
      ],
    }],
  })
  return await Packer.toBuffer(doc)
}

export async function generateXlsx(title: string, content: string): Promise<Buffer> {
  const { Workbook } = requireFn('exceljs')
  const workbook = new Workbook()
  const sheet = workbook.addWorksheet(title.slice(0, 31))
  const rows = content.split('\n').filter(Boolean)
  rows.forEach((row, i) => {
    sheet.getRow(i + 1).values = [row]
  })
  const buffer = await workbook.xlsx.writeBuffer()
  return Buffer.from(buffer)
}

export type Params = z.infer<typeof schema>

export async function execute(
  _params: Params,
): Promise<{ content: { type: string; text: string }[] }> {
    const params = schema.parse(_params)
    const now = new Date().toISOString()

    const document = [
      `# ${params.title}`,
      '',
      `**Type:** ${params.type}`,
      `**Created:** ${now}`,
      params.tags.length > 0 ? `**Tags:** ${params.tags.join(', ')}` : '',
      '',
      '---',
      '',
      params.content,
      '',
      '---',
      `*Generated by document-gen tool*`,
    ]
      .filter(Boolean)
      .join('\n')

    const format = params.format || 'markdown'

    if (format === 'pdf') {
      const buffer = await generatePdf(params.title, document)
      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              filename: `${params.title}.pdf`,
              mimeType: 'application/pdf',
              data: buffer.toString('base64'),
            }),
          },
        ],
      }
    }

    if (format === 'docx') {
      const buffer = await generateDocx(params.title, document)
      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              filename: `${params.title}.docx`,
              mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
              data: buffer.toString('base64'),
            }),
          },
        ],
      }
    }

    if (format === 'xlsx') {
      const buffer = await generateXlsx(params.title, document)
      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              filename: `${params.title}.xlsx`,
              mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
              data: buffer.toString('base64'),
            }),
          },
        ],
      }
    }

    return {
      content: [{ type: 'text', text: document }],
    }
  }



