import { z } from 'zod'

export const name = 'document_gen'

export const description = 'Generate a document in markdown format with optional metadata. Supports various document types like reports, summaries, and notes.'

export const schema = z.object({
  title: z.string().min(1).describe('The document title'),
  content: z.string().min(1).describe('The document content in markdown format'),
  type: z.enum(['report', 'summary', 'note', 'technical']).default('note').describe('The type of document'),
  tags: z.array(z.string()).default([]).describe('Optional tags for the document'),
})

export type Params = z.infer<typeof schema>

export async function execute(_params: Params): Promise<{ content: { type: string; text: string }[] }> {
  const params = schema.parse(_params)
  const now = new Date().toISOString()

  const document = [
    `# ${params.title}`,
    '',
    `**Type:** ${params.type}`,
    `**Created:** ${now}`,
    params.tags.length > 0 ? `**Tags:** ${params.tags.join(', ')}` : '',
    '',
    '---',
    '',
    params.content,
    '',
    '---',
    `*Generated by document-gen tool*`,
  ]
    .filter(Boolean)
    .join('\n')

  return {
    content: [{ type: 'text', text: document }],
  }
}
